# https://docs.docker.com/compose/compose-file/
version: "3.8"
services:
  ########################
  # BenkoBot Midware - For running locally
  ########################
  benkobot-midware:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    entrypoint: npm run start