// flow-typed signature: 598f5e228aa1791c339ad945b2af286d
// flow-typed version: <<STUB>>/immer_v7.0.15/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immer/dist/immer.cjs.development' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.cjs.production.min' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.esm' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.umd.development' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.umd.production.min' {
  declare module.exports: any;
}

declare module 'immer/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immer/dist/immer.cjs.development.js' {
  declare module.exports: $Exports<'immer/dist/immer.cjs.development'>;
}
declare module 'immer/dist/immer.cjs.production.min.js' {
  declare module.exports: $Exports<'immer/dist/immer.cjs.production.min'>;
}
declare module 'immer/dist/immer.esm.js' {
  declare module.exports: $Exports<'immer/dist/immer.esm'>;
}
declare module 'immer/dist/immer.umd.development.js' {
  declare module.exports: $Exports<'immer/dist/immer.umd.development'>;
}
declare module 'immer/dist/immer.umd.production.min.js' {
  declare module.exports: $Exports<'immer/dist/immer.umd.production.min'>;
}
declare module 'immer/dist/index' {
  declare module.exports: $Exports<'immer/dist'>;
}
declare module 'immer/dist/index.js' {
  declare module.exports: $Exports<'immer/dist'>;
}
