// flow-typed signature: df43707ab532f03147a651746e167111
// flow-typed version: <<STUB>>/simple-json-db_v^1.2.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-json-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-json-db' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-json-db/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-json-db/index' {
  declare module.exports: $Exports<'simple-json-db'>;
}
declare module 'simple-json-db/index.js' {
  declare module.exports: $Exports<'simple-json-db'>;
}
declare module 'simple-json-db/test.js' {
  declare module.exports: $Exports<'simple-json-db/test'>;
}
